development:
  adapter: postgresql
  encoding: unicode
  database: tgroup_development
  pool: 5
  username: rbates
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: tgroup_test
  pool: 5
  username: rbates
  password: